pull_request_rules:
  - name: tag no test cases update when update source code
    conditions:
      - files~=^lib/
      - -files~=^t/
    actions:
      label:
        add:
          - no-test-cases
  - name: tag test cases update when update source code
    conditions:
      - files~=^lib/
      - files~=^t/
    actions:
      label:
        remove:
          - no-test-cases
